# Generated by Django 2.2.2 on 2019-06-10 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de autor', max_length=50, verbose_name='Nombre de autor')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Lista de autores',
                'db_table': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(help_text='Digite genero literario', max_length=50, verbose_name='Genero literiario')),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Lista de generos',
                'db_table': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(help_text='Digite genero literario', max_length=50, verbose_name='Ubicacion del libro')),
                ('comentarios', models.TextField(help_text='Digite comentarios sobre sobre la ubicacion', verbose_name='Comentarios sobre la ubicacion')),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Lista de ubicaciones',
                'db_table': 'Ubicacion',
            },
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Digite el titulo del libro', max_length=50, verbose_name='Titulo del libro')),
                ('fecha_compra', models.DateTimeField(help_text='Digite fecha de compra', verbose_name='Fecha de compra')),
                ('sinapsis', models.TextField(help_text='Digite sinapsis del libro', verbose_name='Sinapsis del libro')),
                ('comentarios', models.TextField(help_text='Digite comentarios sobre el libro', verbose_name='Comentarios sobre el libro')),
                ('autor', models.ForeignKey(help_text='Seleccione autor', on_delete=django.db.models.deletion.CASCADE, related_name='libro_autor', to='libros.Autores', verbose_name='Autor')),
                ('genero', models.ForeignKey(help_text='Seleccione genero', on_delete=django.db.models.deletion.CASCADE, related_name='genero_autor', to='libros.Generos', verbose_name='Genero')),
                ('ubicacion', models.ForeignKey(help_text='Seleccione ubicacion', on_delete=django.db.models.deletion.CASCADE, related_name='libro_ubicacion', to='libros.Ubicacion', verbose_name='Ubicacion')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Lista de libros',
                'db_table': 'Libros',
            },
        ),
    ]
